apiVersion: v1

kind: Service

metadata:
  name: kubernetes-cicd-service

spec:
  type: NodePort

  selector:
    app: kubernetes-cicd-app

  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080