
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Check GitHub OIDC claims
      - name: Check GitHub OIDC claims
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com')
            const payload = JSON.parse(
              Buffer.from(token.split('.')[1], 'base64url').toString()
            )
            core.info(JSON.stringify({
              aud: payload.aud,
              sub: payload.sub,
              repository: payload.repository,
              repository_id: payload.repository_id,
              repository_owner: payload.repository_owner,
              repository_owner_id: payload.repository_owner_id,
              ref: payload.ref
            }, null, 2))

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::480111644340:role/GitHubActionsECRRole
          aws-region: us-east-2

      # Step 4: Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t kubernetes-cicd-app:v1 .

      # Step 6: Tag Docker image
      - name: Tag Docker image
        run: |
          docker tag kubernetes-cicd-app:v1 \
            480111644340.dkr.ecr.us-east-2.amazonaws.com/kubernetes-cicd-app:v1

      # Step 7: Push Docker image to ECR
      - name: Push Docker image
        run: |
          docker push \
            480111644340.dkr.ecr.us-east-2.amazonaws.com/kubernetes-cicd-app:v1
